name: binder
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.10

  # HyRiver packages
  - async_retriever>=0.3.1
  - pygeoogc>=0.13.2
  - pygeoutils>=0.13.2
  - py3dep>=0.13.3
  - pynhd>=0.13.2
  - pygeohydro>=0.12.3
  - pydaymet>=0.13.2

  # Optional deps to speed up xarray and daymet
  - bottleneck
  - numba

  # Other third-party deps
  - cartopy
  - datashader
  - mapclassify
  - contextily
  - geoviews
  - hvplot
  - osmnx
  - tqdm
  - pytables
  - ffmpeg
  - jupyterlab_widgets
  - ipywidgets
  - proplot
  - pygmo
  - xarray-spatial
